import { StyleSheet, Dimensions } from 'react-native';
const screenWidth = Dimensions.get('window').width;
const screenHeight = Dimensions.get('window').height;

const currentWaypointStyles = StyleSheet.create({
	container: {
		flex: 1,
	},
	imageStack: {
		width: screenWidth,
		height: screenHeight,
	},
	image: {
		width: '100%',
		height: '100%',
		position: 'absolute',
		top: 0,
	},
	clueImage: {
		display: 'flex',
		position: 'absolute',
		flexDirection: 'column',
		justifyContent: 'center',
		alignItems: 'center',
		width: '100%',
		height: '97%',
		borderColor: '#fff',
		borderWidth: 2,
		marginTop: 50,
		paddingTop: 20,
		borderWidth: 2,
		borderRadius: 25,
	},
	clueSwipe: {
		display: 'flex',
		position: 'absolute',
		flexDirection: 'column',
		justifyContent: 'flex-end',
		alignItems: 'center',
		width: screenWidth - 20,
		height: screenHeight - 30,
		paddingBottom: 30,
		paddingLeft: 10,
		paddingRight: 10,
		marginLeft: 10,
		bottom: 50,
	},
	mapView: {
		flex: 1,
		display: 'flex',
		flexDirection: 'column',
		flexWrap: 'nowrap',
		justifyContent: 'space-around',
		alignItems: 'center',
		marginTop: 50,
		marginBottom: 30,
		paddingBottom: 90,
		paddingTop: 50,
		position: 'relative',
		width: screenWidth - 40,
		borderWidth: 2,
		borderColor: 'white',
		borderRadius: 25,
	},
	mapData: {
		display: 'flex',
		position: 'relative',
		flexDirection: 'column',
		justifyContent: 'space-between',
		alignItems: 'center',
		width: screenWidth - 20,
		height: screenHeight - 40,
		paddingTop: 10,
		paddingBottom: 10,
		paddingLeft: 10,
		paddingRight: 10,
		marginLeft: 10,
	},
	mapData2: {
		display: 'flex',
		position: 'relative',
		flexDirection: 'column',
		justifyContent: 'space-between',
		alignItems: 'center',
		width: screenWidth - 20,
		height: screenHeight - 40,
		paddingTop: 90,
		paddingBottom: 10,
		paddingLeft: 10,
		paddingRight: 10,
		marginLeft: 10,
	},

	button: {
		position: 'absolute',
		left: 0,
		bottom: 50,
		zIndex: 999,
	},
	acornContainer: {
		position: 'absolute',
		bottom: 110,
		right: 35,
		flexDirection: 'column-reverse',
	},
	acorn: {
		height: 40,
		width: 40,
		marginTop: 5,
		borderRadius: 10,
	},
	smallTxt: {
		fontSize: 20,
		fontWeight: '400',
		paddingLeft: 10,
		lineHeight: 20,
		color: '#fff',
	},
	mapBtn: {
		display: 'flex',
		margin: 10,
		left: 10,
		bottom: 10,
		borderRadius: 10,
		width: 150,
		position: 'relative',
		height: 40,
		alignItems: 'center',
		justifyContent: 'flex-end',
	},
	woodenBtn: {
		position: 'absolute',
		top: 0,
		left: 0,
		right: 0,
		bottom: 0,
		justifyContent: 'center',
		alignItems: 'center',
	},
	mapBtnText: {
		display: 'flex',
		position: 'absolute',
		padding: 'auto',
		margin: 'auto',
		fontWeight: '700',
		flexDirection: 'row',
		alignItems: 'center',
		fontSize: 15,
		color: '#fff',
	},
	clueSwipeInstruction: {
		position: 'absolute',
		bottom: 20,
		fontSize: 22,
		padding: 20,
		color: '#ffffff',
		fontWeight: '500',
		backgroundColor: '#867957',
		opacity: 0.9,
	},
	mapSwipeBtn: {
		bottom: 25,
	},
	clueSwipeBtn: {
		bottom: -80,
	},
});

export default currentWaypointStyles;
